import {StyleSheet} from 'react-native';
import Colors from '../../constants/colors';
import colors from '../../constants/colors';
const OwnerRentalstyles = StyleSheet.create({
  mainContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: Colors.black,
  },
  MainTitleText: {
    alignItems: 'center',
    fontFamily: 'Poppins-Bold',
    color: Colors.black,
    marginLeft: '5%',
    marginTop: 10,
    fontSize: 24,
  },
  ScrollContainer: {
    height: '75%',
    width: '95%',
    marginTop: 10,
    backgroundColor: colors.black,
    borderRadius: 15,
    marginLeft: 10,
  },
  noAddressContainer1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  titleTextContainer1: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    marginLeft: 60,
  },
  imageS1: {
    width: 300,
    height: 300,
    borderRadius: 130,
    marginLeft: -25,
  },
  textContainer1: {
    alignItems: 'center',
  },
  noAddressText1: {
    fontWeight: '500',
    fontSize: 20,
    marginTop: 20,
    marginBottom: 10,
    color: 'white',
  },
  cardContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.Inputtext,
    borderRadius: 10,
    marginLeft: 10,
    marginBottom: 10,
    height: 150,
    width: '90%',
    elevation: 4,
  },
  imageContainer: {
    width: '30%',
    height: '82%',
    marginTop: 10,
    marginLeft: 10,
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 3,
  },
  subContainer: {
    height: '100%',
    width: '85%',
  },
  cardTextContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '85%',
    marginLeft: 10,
    marginTop: 10,
  },
  productName: {
    fontSize: 14,
    marginLeft: 10,
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    marginTop: -30,
  },
  price: {
    fontSize: 14,
    marginLeft: 10,
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    marginTop: 10,
  },
  name: {
    fontSize: 12,
    color: 'black',
    fontFamily: 'Poppins-SemiBold',
    marginRight: 10,
  },
  priceText: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
    color: Colors.buttonColor,
    marginRight: 50,
  },
  sizeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 40,
    height: 20,
    marginLeft: 6,
    marginTop: 15,
  },
  sizeText: {
    fontSize: 12,
    color: 'black',
    fontFamily: 'Poppins-SemiBold',
    marginHorizontal: 5,
  },
  detailsdescription: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
  },
  card: {
    // height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    // backgroundColor: Colors.white,
    width: '90%',
    height: 100,
    // borderWidth: 0.2,
    borderColor: '#8E8E8E',
    // backgroundColor: 'pink',
    alignSelf: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
    borderRadius: 12,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  arrowIcon: {
    marginLeft: '70%',
  },
});
export default OwnerRentalstyles;
