import {StyleSheet} from 'react-native';
import Colors from '../../../constants/colors';
import colors from '../../../constants/colors';
const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.main,
    width: '100%',
    height: '100%',
  },
  cardContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.Inputtext,
    borderRadius: 10,
    marginLeft: 10,
    marginBottom: 10,
    height: 150,
    width: '90%',
    elevation: 4,
  },
  MainTitleText: {
    alignItems: 'center',
    fontFamily: 'Poppins-Bold',
    color: Colors.black,
    marginLeft: '42%',
    marginTop: 10,
    fontSize: 24,
  },
  images: {
    width: 64,
    height: 100,
    marginRight: 10,
    resizeMode: 'cover',
    borderRadius: 5,
  },
  cardTextContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '85%',
    marginLeft: 10,
    marginTop: 10,
  },
  name: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
    marginRight: 10,
  },
  subContainer: {
    height: '100%',
    width: '85%',
  },
  backContainer: {
    backgroundColor: Colors.Inputtext,
    height: 40,
    width: 40,
    alignItems: 'center',
    borderRadius: 100,
    justifyContent: 'center',
  },
  Backicon: {
    marginLeft: 10,
  },
  disabled: {
    backgroundColor: Colors.gray,
  },
  productname: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
  },
  textContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addButton: {
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: Colors.iconscolor,
  },
  rentButton: {
    backgroundColor: Colors.iconscolor,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 80,
    marginTop: 10,
    height: 25,
    justifyContent: 'space-between',
  },
  DateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#D9D9D9',
    width: 72,
    height: 20,
    marginLeft: 10,
    marginBottom: 10,
    justifyContent: 'space-between',
  },
  quantityButton: {
    borderRadius: 100,
    height: 24,
    width: 24,
    backgroundColor: Colors.buttonColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 16,
    color: Colors.white,
    fontWeight: 'bold',
  },
  sizeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 40,
    height: 20,
    marginLeft: 6,
    marginTop: 15,
  },
  sizeButton: {
    backgroundColor: colors.white,
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: colors.iconscolor,
  },
  GrandtotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
    marginLeft: 25,
  },
  sizeText: {
    fontSize: 12,
    color: 'black',
    fontFamily: 'Poppins-SemiBold',
    marginHorizontal: 5,
  },
  errorContainer: {
    backgroundColor: '#FDD',
    padding: 10,
    borderRadius: 5,
  },
  errorText: {
    color: colors.red,
    fontWeight: 'bold',
    fontSize: 16,
  },
  container: {
    backgroundColor: Colors.lavander,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  TextTotal: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: 5,
    color: Colors.iconscolor,
  },
  TextGrand: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: -20,
    left: 20,
    color: Colors.iconscolor,
    fontSize: 18,
  },
  RemoveButton: {
    height: 25,
    width: '40%',
    backgroundColor: Colors.buttonColor,
    marginTop: 10,
    borderRadius: 5,
    color: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  RemoveContainer: {
    marginTop: 10,
  },
  UpdateButton: {
    height: 20,
    width: 40,
    backgroundColor: 'white',
    marginLeft: 30,
    borderRadius: 3,
    color: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  PaymentButton: {
    height: 60,
    width: '90%',
    backgroundColor: Colors.buttonColor,
    marginTop: 10,
    marginLeft: 20,
    borderRadius: 100,
    fontFamily: 'Poppins-Medium',
    color: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  PaymentButtonText: {
    color: Colors.white,
    fontSize: 16,
    height: 25,
    fontFamily: 'Poppins-Medium',
    justifyContent: 'center',
  },
  RemoveButtonText: {
    color: Colors.white,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    justifyContent: 'center',
  },
  UpdateButtonText: {
    color: Colors.iconscolor,
    fontSize: 9,
    fontWeight: '900',
    justifyContent: 'center',
  },
  removeAndQuantity: {
    flexDirection: 'row',
    marginLeft: 12,
    width: '70%',
    marginTop: 15,
    justifyContent: 'space-between',
  },
  titleContainer: {
    height: 30,
    width: '100%',
    marginLeft: 17,
    borderRadius: 5,
  },
  titleText: {
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: Colors.black,
    marginLeft: 5,
  },
  CartText: {
    color: Colors.black,
    marginTop: 20,
    fontFamily: 'Poppins-Bold',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
    marginLeft: 140,
  },
  ScrollContainer: {
    height: '66%',
    width: '100%',
    marginTop: 16,
    marginLeft: 10,
  },

  detailsdescription: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
  },
  coupons: {
    height: '10%',
    width: '90%',
    backgroundColor: Colors.gray,
    borderRadius: 9,
    marginTop: -40,
    marginBottom: 7,
    marginLeft: 20,
    flexDirection: 'row',
  },
  couponsText: {
    color: Colors.white,
    fontSize: 15,
    fontFamily: 'Poppins-SemiBold',
    marginTop: 15,
    marginLeft: 10,
  },
  cardContaineramount: {
    borderWidth: 1,
    borderColor: Colors.containerColor,
    backgroundColor: Colors.containerColor,
    borderRadius: 5,
    padding: 10,
    height: 48,
    width: 355,
    left: 20,
    top: -10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 3,
  },
  imageContainer: {
    width: '30%',
    height: '82%',
    marginTop: 10,
    marginLeft: 10,
  },
  priceText: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
    color: Colors.buttonColor,
    marginRight: 50,
  },
  priceTotalText: {
    fontSize: 16,
    width: '100%',
    color: Colors.black,
    marginLeft: 40,
    fontFamily: 'Poppins-Medium',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    left: -47,
  },
  GrandtotalText: {
    color: Colors.black,
    fontFamily: 'Poppins-Medium',
    marginLeft: 5,
    fontSize: 16,
  },
  quantityTxt: {
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.black,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
  DateTxt: {
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.black,
    fontSize: 9,
    width: 55,
    height: 12,
    marginLeft: 7,
    fontFamily: 'Poppins-Medium',
  },
  button: {
    backgroundColor: '#fff',
    paddingHorizontal: 60,
    paddingVertical: 5,
    borderRadius: 5,
  },

  buttonText: {
    fontSize: 9,
    fontWeight: 'bold',
    marginLeft: 5,
    marginRight: 5,
  },

  noAddressContainer1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  titleTextContainer1: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    marginLeft: 60,
  },
  imageS1: {
    width: 300,
    height: 300,
    borderRadius: 130,
    marginLeft: -25,
  },
  textContainer1: {
    alignItems: 'center',
  },
  noAddressText1: {
    fontWeight: '500',
    fontSize: 20,
    marginTop: 20,
    marginBottom: 10,
    color: 'white',
  },

  lottiecontainer: {
    flex: 1,
    alignItems: 'center',
  },
  Lottiestyle: {},
  lottie: {
    height: 200,
    width: 200,
    alignSelf: 'center',
    marginTop: '50%',
    justifyContent: 'center',
  },
  Disabled: {
    backgroundColor: Colors.gray,
  },
  datepickerStyle: {
    backgroundColor: Colors.lightWhite,
    width: 75,
    height: 25,
    borderRadius: 8,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  datepickerTextstyle: {color: Colors.black, fontSize: 10},
});
export default styles;
